config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#show'
  resources :works do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :work

  validates :title, presence: true
  validates :scheduled_date, presence: true
  validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :client_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    @work = Work.find(params[:work_id])

    if @work.user != current_user
      redirect_to user_path
    end
  end

  def edit
    @task = Task.find(params[:id])
    @work = Work.find(params[:work_id])
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to work_path(@task.work)
    else
      @work = Work.find(params[:work_id])
      render :new
    end
  end

  def update
  end

  def destroy
    Task.find(params[:id]).destroy

    work = Work.find(params[:work_id])
    redirect_to work_path(work)
  end

  private
  def task_params
    params.require(:task).permit(:title, :scheduled_date, :due_date).merge(work_id: params[:work_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @tasks = Task.all.order(:scheduled_date).order(:title)

    if @tasks.size > 0
      @first_date = @tasks.first.scheduled_date
      @last_date = @tasks.last.scheduled_date
    else
      @first_date = 0
      @last_date = -1
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all.order(:client_name)
  end

  def show
    @work = Work.find(params[:id])
  end

  def new
    @work = Work.new
  end

  def edit
    @work = Work.find(params[:id])
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to work_path(@work)
    else
      render :new
    end
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to work_path(@work)
    else
      render :edit
    end
  end

  def destroy
    work = Work.find(params[:id])
    work.destroy
    redirect_to works_path
  end

  private
  def work_params
    params.require(:work).permit(:client_name, :contact_url, :document_url, :due, :memo).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "WorkManager", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 text-dark">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "作業カレンダー", root_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "案件リスト", works_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "案件登録", new_work_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <main class="container mt-4 mt-mb-3">
      <%= yield %>
    </main>

    <footer>

    </footer>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [work, task] do |f| %>
  <div>
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= f.label :scheduled_date, class: "form-label" %>
    <%= f.date_field :scheduled_date, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= f.label :due_date, class: "form-label" %>
    <%= f.date_field :due_date, class: "form-control" %>
  </div>

  <div class="d-grid mt-5">
    <%= f.submit "送信", class: "btn btn-success" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>タスク編集 (<%= @work.client_name %>)</h1>
      <%= render 'form', work: @work, task: @task %>

      <div class="d-grid mt-3">
        <%= link_to "削除", work_task_path(@work, @task), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger"%>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>新規タスク (<%= @work.client_name %>)</h1>
      <%= render 'form', work: @work, task: @task %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="raw">
    <div class="col">
      <h1>作業カレンダー</h1>

      <% (@first_date .. @last_date).each do |date| %>
        <div>
          <h3 class="bg-secondary text-light m-0 py-1 ps-3">
            <%= l date %>
          </h3>

          <div class="bg-light d-flex flex-wrap py-2">
            <% @tasks.where(scheduled_date: date).each do |task| %>
              <%= link_to work_path(task.work), class: "btn btn-outline-secondary shadow text-start m-2", style: "width: 9.5rem" do %>
                <p class="m-0 text-truncate"><%= task.title %></p>
                <h4 class="m-0 text-truncate"><%= task.work.client_name %></h4>
                <p class="m-0">締切：<%= l task.due_date %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/works/_form.html.erb
<%= form_with model: work do |f| %>
  <div>
    <%= f.label :client_name, class: "form-label" %>
    <%= f.text_field :client_name, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= f.label :due, class: "form-label" %>
    <%= f.date_field :due, class: "form-control" %>
  </div>

  <hr>

  <div class="mt-3">
    <%= f.label :contact_url, class: "form-label" %>
    <%= f.url_field :contact_url , class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= f.label :document_url, class: "form-label" %>
    <%= f.url_field :document_url, class: "form-control" %>
  </div>

  <hr>

  <div class="mt-3">
    <%= f.label :memo, class: "form-label" %>
    <%= f.text_area :memo, class: "form-control" %>
  </div>

  <div class="d-grid mt-5">
    <%= f.submit "送信", class: "btn btn-success" %>
  </div>
<% end %>

app/views/works/create.html.erb
<h1>Works#create</h1>
<p>Find me in app/views/works/create.html.erb</p>

app/views/works/destroy.html.erb
<h1>Works#destroy</h1>
<p>Find me in app/views/works/destroy.html.erb</p>

app/views/works/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>案件編集</h1>
      <%= render 'form', work: @work %>
    </div>
  </div>
</div>

app/views/works/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>案件一覧</h1>

      <div class="d-flex flex-wrap">
        <% @works.each do |work| %>
          <%= link_to work_path(work), class: "btn btn-outline-secondary shadow m-2 pt-3", style: "width: 9.5rem; height: 10rem" do %>
            <h3 class="text-truncate"><%= work.client_name %></h3>
            <p class="mb-0 text-start">memo:</p>
            <p class="mb-0 text-start text-break text-wrap text-truncate" style="max-height: 3.2rem; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2"><%= work.memo %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/works/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>案件登録</h1>
      <%= render 'form', work: @work %>
    </div>
  </div>
</div>

app/views/works/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-4">
      <h1 class="text-truncate"><%= @work.client_name %></h1>

      <% if @work.due.present? %>
        <p>納期：<%= l @work.due %></p>
      <% else %>
        <p>納期未設定</p>
      <% end %>

      <div class="text-end">
        <%= link_to "編集", edit_work_path(@work), class: "btn btn-outline-secondary" %>
        <%= link_to "削除", work_path(@work), method: :delete, class: "btn btn-outline-secondary" %>
      </div>

      <hr>

      <div class="d-grid gap-2">
        <% if @work.contact_url.present? %>
          <%= link_to @work.contact_url, class: "btn btn-outline-secondary" do %>
            <i class="fa-solid fa-address-book fa-2x"></i>
          <% end %>
        <% else %>
          <%= link_to "連絡先未設定", @work.document_url, class: "btn btn-outline-secondary disabled", "area-disabled" => true %>
        <% end %>

        <% if @work.document_url.present? %>
          <%= link_to @work.document_url, class: "btn btn-outline-secondary" do %>
            <i class="fa-solid fa-file fa-2x"></i>
          <% end %>
        <% else %>
          <%= link_to "資料未設定", @work.document_url, class: "btn btn-outline-secondary disabled", "area-disabled" => true %>
        <% end %>
      </div>

      <hr>

      <div>
        <p class="mb-0 text-truncate">memo:</p>
        <p class="text-break text-wrap"><%= @work.memo %></p>
      </div>
    </div>


    <div class="col-md-7 offset-md-1 mt-3 mt-md-0">
      <h2>作業リスト</h2>

      <div class="text-end">
        <%= link_to "新規", new_work_task_path(@work), class: "btn btn-outline-secondary" %>
      </div>

      <div class="d-grid gap-2 mt-3">
        <% @work.tasks.order(:scheduled_date).each do |task| %>
          <%= link_to edit_work_task_path(@work, task), class: "btn btn-outline-secondary shadow" do %>
            <h3 class="text-start"><%= task.title %></h3>

            <div class="text-end">
              <p class="m-0">作業予定日：<%= l task.scheduled_date %> | 提出締切：<%= l task.due_date %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/works/update.html.erb
<h1>Works#update</h1>
<p>Find me in app/views/works/update.html.erb</p>